// Code generated by MockGen. DO NOT EDIT.
// Source: app.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aquareo "github.com/pedrobfernandes/aquareo/internal/aquareo"
)

// MockWebServer is a mock of WebServer interface.
type MockWebServer struct {
	ctrl     *gomock.Controller
	recorder *MockWebServerMockRecorder
}

// MockWebServerMockRecorder is the mock recorder for MockWebServer.
type MockWebServerMockRecorder struct {
	mock *MockWebServer
}

// NewMockWebServer creates a new mock instance.
func NewMockWebServer(ctrl *gomock.Controller) *MockWebServer {
	mock := &MockWebServer{ctrl: ctrl}
	mock.recorder = &MockWebServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebServer) EXPECT() *MockWebServerMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockWebServer) Start(addr string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", addr)
}

// Start indicates an expected call of Start.
func (mr *MockWebServerMockRecorder) Start(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWebServer)(nil).Start), addr)
}

// Stop mocks base method.
func (m *MockWebServer) Stop(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", ctx)
}

// Stop indicates an expected call of Stop.
func (mr *MockWebServerMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWebServer)(nil).Stop), ctx)
}

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Sensor mocks base method.
func (m *MockController) Sensor(sensorId string) aquareo.Sensor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sensor", sensorId)
	ret0, _ := ret[0].(aquareo.Sensor)
	return ret0
}

// Sensor indicates an expected call of Sensor.
func (mr *MockControllerMockRecorder) Sensor(sensorId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sensor", reflect.TypeOf((*MockController)(nil).Sensor), sensorId)
}

// Sensors mocks base method.
func (m *MockController) Sensors() []aquareo.Sensor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sensors")
	ret0, _ := ret[0].([]aquareo.Sensor)
	return ret0
}

// Sensors indicates an expected call of Sensors.
func (mr *MockControllerMockRecorder) Sensors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sensors", reflect.TypeOf((*MockController)(nil).Sensors))
}

// Store mocks base method.
func (m *MockController) Store() aquareo.Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store")
	ret0, _ := ret[0].(aquareo.Store)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockControllerMockRecorder) Store() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockController)(nil).Store))
}

// MockGPIODriver is a mock of GPIODriver interface.
type MockGPIODriver struct {
	ctrl     *gomock.Controller
	recorder *MockGPIODriverMockRecorder
}

// MockGPIODriverMockRecorder is the mock recorder for MockGPIODriver.
type MockGPIODriverMockRecorder struct {
	mock *MockGPIODriver
}

// NewMockGPIODriver creates a new mock instance.
func NewMockGPIODriver(ctrl *gomock.Controller) *MockGPIODriver {
	mock := &MockGPIODriver{ctrl: ctrl}
	mock.recorder = &MockGPIODriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPIODriver) EXPECT() *MockGPIODriverMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockGPIODriver) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockGPIODriverMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGPIODriver)(nil).Close))
}

// Open mocks base method.
func (m *MockGPIODriver) Open() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open")
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open.
func (mr *MockGPIODriverMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockGPIODriver)(nil).Open))
}

// MockSensor is a mock of Sensor interface.
type MockSensor struct {
	ctrl     *gomock.Controller
	recorder *MockSensorMockRecorder
}

// MockSensorMockRecorder is the mock recorder for MockSensor.
type MockSensorMockRecorder struct {
	mock *MockSensor
}

// NewMockSensor creates a new mock instance.
func NewMockSensor(ctrl *gomock.Controller) *MockSensor {
	mock := &MockSensor{ctrl: ctrl}
	mock.recorder = &MockSensorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSensor) EXPECT() *MockSensorMockRecorder {
	return m.recorder
}

// CurrentValue mocks base method.
func (m *MockSensor) CurrentValue() float32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentValue")
	ret0, _ := ret[0].(float32)
	return ret0
}

// CurrentValue indicates an expected call of CurrentValue.
func (mr *MockSensorMockRecorder) CurrentValue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentValue", reflect.TypeOf((*MockSensor)(nil).CurrentValue))
}

// Id mocks base method.
func (m *MockSensor) Id() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id.
func (mr *MockSensorMockRecorder) Id() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockSensor)(nil).Id))
}

// Refresh mocks base method.
func (m *MockSensor) Refresh() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh")
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockSensorMockRecorder) Refresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockSensor)(nil).Refresh))
}

// MockSensorCommander is a mock of SensorCommander interface.
type MockSensorCommander struct {
	ctrl     *gomock.Controller
	recorder *MockSensorCommanderMockRecorder
}

// MockSensorCommanderMockRecorder is the mock recorder for MockSensorCommander.
type MockSensorCommanderMockRecorder struct {
	mock *MockSensorCommander
}

// NewMockSensorCommander creates a new mock instance.
func NewMockSensorCommander(ctrl *gomock.Controller) *MockSensorCommander {
	mock := &MockSensorCommander{ctrl: ctrl}
	mock.recorder = &MockSensorCommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSensorCommander) EXPECT() *MockSensorCommanderMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockSensorCommander) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockSensorCommanderMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSensorCommander)(nil).Start))
}

// Stop mocks base method.
func (m *MockSensorCommander) Stop(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", ctx)
}

// Stop indicates an expected call of Stop.
func (mr *MockSensorCommanderMockRecorder) Stop(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSensorCommander)(nil).Stop), ctx)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ReadAll mocks base method.
func (m *MockStore) ReadAll(bucket string, size int) ([]aquareo.MetricEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", bucket, size)
	ret0, _ := ret[0].([]aquareo.MetricEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockStoreMockRecorder) ReadAll(bucket, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockStore)(nil).ReadAll), bucket, size)
}

// Store mocks base method.
func (m *MockStore) Store(bucket string, entry aquareo.MetricEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", bucket, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockStoreMockRecorder) Store(bucket, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockStore)(nil).Store), bucket, entry)
}
